'use strict';

// Kept as source modules so pkg embeds them with the executable.
const webAssets = {
  'index.html': '<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ag-box 同步</title><link rel="stylesheet" href="/web/styles.css"></head><body><main><h1>ag-box 本地同步</h1><p id="notice">正在读取本机项目…</p><section><h2>项目</h2><ul id="projects"></ul></section><section><h2>同步</h2><label>项目路径 <input id="project" autocomplete="off"></label><button id="sync">同步</button><pre id="task" aria-live="polite"></pre></section><section><h2>托管模式</h2><p>即将推出。当前版本仅支持由你自行配置的存储凭证。</p></section></main><script src="/web/app.js"></script></body></html>',
  'app.js': "'use strict';const token=location.hash.slice(1);history.replaceState(null,'',location.pathname);const auth={Authorization:`Bearer ${token}`};const $=id=>document.getElementById(id);async function api(url,options={}){const r=await fetch(url,{...options,headers:{...auth,...(options.headers||{})}});const body=await r.json();if(!r.ok)throw new Error(body.error||'请求失败');return body}async function projects(){try{const data=await api('/api/projects');$('projects').replaceChildren(...data.projects.map(p=>{const li=document.createElement('li');li.textContent=`${p.id} — ${p.path}`;return li}));$('notice').textContent=data.projects.length?'仅显示本机已登记的项目。':'尚未登记项目，请在命令行运行 sessions init。'}catch(e){$('notice').textContent=e.message}}$('sync').onclick=async()=>{try{const data=await api('/api/sync',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({operation:'sync',project:$('project').value})});const id=data.task.id;const poll=async()=>{const t=(await api(`/api/tasks/${id}`)).task;$('task').textContent=JSON.stringify(t,null,2);if(['queued','running'].includes(t.state))setTimeout(poll,500);else projects()};poll()}catch(e){$('task').textContent=e.message}};projects();",
  'styles.css': ':root{font-family:system-ui,sans-serif;color:#1f2937;background:#f8fafc}main{max-width:760px;margin:3rem auto;padding:0 1rem}section{background:#fff;border:1px solid #dbe3ef;border-radius:8px;padding:1rem;margin-top:1rem}input{min-width:22rem;padding:.5rem}button{padding:.5rem .9rem}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#f1f5f9;padding:.75rem;border-radius:4px}',
};
module.exports = { webAssets };
